version: 2
updates:
  - package-ecosystem: "npm"
    directories: 
      - "/"
      - "/template"  
    ignore:
      - dependency-name: "next"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    target-branch: "develop"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
