version: 2
updates:
  - package-ecosystem: "npm"
    directories: 
      - "/"
      - "/template"  
    ignore:
      - dependency-name: "next"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "develop"
    groups:
      angular:
        applies-to: version-updates
        patterns:
        - "@splunk*"
        
  - package-ecosystem: "github-actions"
    target-branch: "develop"
    directory: "/"
    schedule:
      interval: "weekly"
